# AUTOGENERATED! DO NOT EDIT! File to edit: Cox_Proportional_Hazard.ipynb (unless otherwise specified).

__all__ = ['ProportionalHazard']

# Cell
from .ph import PieceWiseHazard
from ..utils import GetAttr
from ..losses import hazard_loss

import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np

# torch.Tensor.ndim = property(lambda x: x.dim())

# Cell
class ProportionalHazard(nn.Module):
    """
    Hazard proportional to time and feature component as shown above.
    parameters:
    - breakpoints: time points where hazard would change
    - max_t: maximum point of time to plot to.
    - dim: number of input dimensions of x
    - h: (optional) number of hidden units (for x only).
    """
    def __init__(self, breakpoints, max_t, dim, h=()):
        super().__init__()
        self.baseλ = PieceWiseHazard(breakpoints, max_t)
        nodes = (dim,) + h + (1,)
        self.layers = [nn.Linear(a,b, bias=False)
                       for a,b in zip(nodes[:-1], nodes[1:])]
        self.max_t = max_t
#         self.default = self.baseλ # used for delegation

    def forward(self, t, t_section, x):
        # get the Kaplan Meier estimates
        logλ, Λ = self.baseλ(t, t_section)

        for layer in self.layers[:-1]:
            x = F.relu(layer(x))
        log_hazard = self.layers[-1](x)

        logλ += log_hazard
        Λ = torch.exp(log_hazard + torch.log(Λ))
        return logλ, Λ

    def plot_survival_function(self, x):
        with torch.no_grad():
            x = torch.Tensor(x)
            if len(x.shape) < 2:
                x = x[None, :]
            # get the times and time sections for survival function
            t_query = np.arange(self.max_t+10)
            breakpoints = self.baseλ.breakpoints[1:].cpu().numpy()
            t_sec_query = np.searchsorted(breakpoints, t_query)
            # convert to pytorch tensors
            t_query = torch.Tensor(t_query)[:,None]
            t_sec_query = torch.LongTensor(t_sec_query)

            # calculate cumulative hazard according to above
            λ, cum_haz = self.forward(t_query, t_sec_query, x)
            surv_fun = torch.exp(-cum_haz)

        # plot
        plt.figure(figsize=(12,5))
        plt.plot(t_query, surv_fun)
        plt.xlabel('Time')
        plt.ylabel('Survival Probability')
        plt.show()