# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"gumbel_logpdf": "AFT_error_distributions.ipynb",
         "gumbel_logcdf": "AFT_error_distributions.ipynb",
         "gaussian_logpdf": "AFT_error_distributions.ipynb",
         "gaussian_logcdf": "AFT_error_distributions.ipynb",
         "get_dists": "AFT_error_distributions.ipynb",
         "AFT": "AFT_models.ipynb",
         "KaplanMeier": "KaplanMeier.ipynb",
         "aft_loss": "Losses.ipynb",
         "hazard_loss": "Losses.ipynb",
         "TestData": "data.ipynb",
         "Data": "data.ipynb",
         "TestDataFrame": "data.ipynb",
         "DataFrame": "data.ipynb",
         "create_db": "data.ipynb",
         "create_test_dl": "data.ipynb",
         "ProportionalHazard": "hazard.Cox.ipynb",
         "torch.Tensor.ndim": "hazard.PiecewiseHazard.ipynb",
         "PieceWiseHazard": "hazard.PiecewiseHazard.ipynb",
         "Model": "model.ipynb"}

modules = ["models/error_dist.py",
           "models/aft.py",
           "models/km.py",
           "losses.py",
           "data.py",
           "models/cox.py",
           "models/ph.py",
           "model.py"]

doc_url = "https://sachinruk.github.io/torchlife/"

git_url = "https://github.com/sachinruk/torchlife/tree/master/"

def custom_doc_links(name): return None
