# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"KaplanMeier": "20_KaplanMeier.ipynb",
         "torch.Tensor.ndim": "55_hazard.PiecewiseHazard.ipynb",
         "PieceWiseHazard": "55_hazard.PiecewiseHazard.ipynb",
         "ProportionalHazard": "59_hazard.Cox.ipynb",
         "AFT": "60_AFT_models.ipynb",
         "gumbel_logpdf": "65_AFT_error_distributions.ipynb",
         "gumbel_logcdf": "65_AFT_error_distributions.ipynb",
         "gaussian_logpdf": "65_AFT_error_distributions.ipynb",
         "gaussian_logcdf": "65_AFT_error_distributions.ipynb",
         "get_distribution": "65_AFT_error_distributions.ipynb",
         "get_breakpoints": "80_data.ipynb",
         "TestData": "80_data.ipynb",
         "Data": "80_data.ipynb",
         "TestDataFrame": "80_data.ipynb",
         "DataFrame": "80_data.ipynb",
         "create_db": "80_data.ipynb",
         "create_test_dl": "80_data.ipynb",
         "ModelHazard": "90_model.ipynb",
         "ModelAFT": "90_model.ipynb",
         "aft_loss": "95_Losses.ipynb",
         "hazard_loss": "95_Losses.ipynb"}

modules = ["models/km.py",
           "models/ph.py",
           "models/cox.py",
           "models/aft.py",
           "models/error_dist.py",
           "data.py",
           "model.py",
           "losses.py"]

doc_url = "https://sachinruk.github.io/torchlife/"

git_url = "https://github.com/sachinruk/torchlife/tree/master/"

def custom_doc_links(name): return None
